### ISSUE TITLE
Missing file MUD.MIC

### ISSUE THREAD

**Issue by quentinnuk** [PDP-10/MUD1#2]
There appears to be a missing file MUD.MIC which is important if you want to compile the source as it specifies the compile time and linker parameters. The list of files in MUD.SUB specifies this file as needed.

**Comment by larsbrinkhoff** [comment]
I'll check with Bartle.

**Comment by larsbrinkhoff** [comment]
He sent me a scan of MUD.MIC.  I checked in the jpg file.

**Comment by larsbrinkhoff** [comment]
I see now a piece has been teared off.  Is it usable?

**Comment by quentinnuk** [comment]
Ive typed it in and put it in the master. The sheets overlap so I think it is all there.  I’ll see if it runs later but it probably has errors from my typing.
