### ISSUE TITLE
Incomplete

### ISSUE THREAD

**Issue by quentinnuk** [PDP-10/MUD1#3]
This scan is incomplete. I have received a full scan from Richard Bartle which is four pages and I have re-typed it as MUD.MIC

**Comment by larsbrinkhoff** [comment]
Great!  When you have checked the spelling, would you please submit it for inclusion here?

**Comment by JohnForecast** [comment]
The files here do not reflect the actual contents of MUD.tap. In particular, MUD.MIC is missing (the one on the tape will produce a functional executable image after a few minor edits) and MBOOTS.MAC consists of 3 concatenated files; MBOOTS.MAC, POWER.BCL and DBADAT.MAC.

**Comment by larsbrinkhoff** [comment]
Thank you @JohnForecast!  I wasn't aware there was a difference.  The files comes from a zip file from Bartle.

@quentinnuk, it seems you may be better off using the files in the tape image!

**Comment by JohnForecast** [comment]
Stanford has a zip file from Bartle with the same problem - probably the same zip file. The tape distribution contains a .MAS file (sort of an early zip file) with the last 3 files being MBOOTS.MAC, POWER.BCL and DBADAT.MAC. Maybe there was a glitch when those files were last extracted - I had no problems extracting under TOPS-10.

**Comment by larsbrinkhoff** [comment]
@JohnForecast, if you could provide the missing files, that would be much appreciated!  (I'm not a TOPS-10 user myself.)

**Comment by JohnForecast** [comment]
Here's a zip file of the missing files along with a replacement for MBOOTS.MAC which is corrupted.
[MUD1.zip](https://github.com/PDP-10/MUD1/files/1885766/MUD1.zip)

**Comment by JohnForecast** [comment]
BTW, the MUD.MIC in the zip file has been modified to work on a vanilla TOPS-10 7.04 system, removing some of the Essex local configuration settings. Let me know if you want the original file instead.

**Comment by larsbrinkhoff** [comment]
Thank you.  I added these three files, and removed the jpg.

The contents of MBOOTS.MAC is a bit different.  The one from the zip file was written mostly in lower case, wereas the one from the tape was mostly upper case.  Maybe there are other changes too, I didn't inspect it very closely.

**Comment by larsbrinkhoff** [comment]
@quentinnuk, @JohnForecast,

If you actually build MUD from the old or the new files, I'd like to hear about your experience.  Did they work as is, or were edits necessary?

**Comment by larsbrinkhoff** [comment]
Oh, I see now that @quentinnuk has updated some files in the repository.  I should not undo those changes.

**Comment by quentinnuk** [comment]
@larsbrinkhoff @JohnForecast I think the files form the tape are more accurate and correct than anything I have produced, and my typed in MUD.MIC certainly has errors. I will be trying a build from the tape files in the near future to confirm, just trying to find the time.

**Comment by JohnForecast** [comment]
The original MUD.MIC file used 2 commands; NSAVE and NSSAVE to save various components to disk. I had never seen these commands and assumed they were Essex specific additions. Further investigation led me to find out they were standard DEC commands in 7.01 which saves memory in non-shareable .EXE files. By 7.04, these commands are gone. I'm not sure how and where MUD maintains its database, but other games on TOPS-10 have been known to write back into the high segment of the .EXE file. It's possible that we may need to go back to 7.01 (if a kit is available) in order to build MUD.

**Comment by larsbrinkhoff** [comment]
I'm going to copy @rcornwell about older TOPS-10 versions.  Is there a 7.01 out there?

**Comment by rcornwell** [comment]
I have partial 4.5, 4.72. Pretty much a broken 5.03. A working 6.03. There is no 7.01 or 7.02 surviving.

Starting in 6.0x there are 6 save commands. OSAVE, OSSAVE (save in old format .SAV, .HGH, .LOW and .SHR), SAVE, SSAVE, NSAVE, NSSAVE (save in new format or .EXE).

Prior to 6.01 TOPS10 used (.SAV or .LOW & .HGH for non-shared and .SHR for shared High segments.)

**Comment by larsbrinkhoff** [comment]
Looks like we can get TOPS-10 5.07 soon.

**Comment by quentinnuk** [comment]
@larsbrinkhoff @JohnForecast I have mostly cracked the MUD difficulties and got it to run unmodified from the tape copy. The key to this was to create a PPN [2011,2776] (Richard Bartle's Essex PPN) and ru mud from there. The profile has to have ENQ-DEQ and IPCF quotas.  There are further things to crack, for example I did have it running from [2011,2011] at one stage and from memory [2653,2653] was the guest account but currently it doesn't start from either of those, instead giving the can't access F.MUD error using the pre-compiled binaries. Still, if you want to see it work login to [2011,2776] with the MUD tape restored and:
```
.login richard
Job 3  PDP10  TTY1
Password: 
[LGNLAS Last access to [2011,2776] succeeded on 13-Apr-118:15:25:59]
15:37   13-Apr-118   Friday

.ru mud


 
ESSEX UNIVERSITY: Multi-User Dungeon
                                     
This Mud created: 28th February 1984 at 20:50:58
Welcome! By what name shall I call you?
*richard
Your last game was today at 15:26:53.
Hello again, Richard the arch-wizard!
                                      
^C trap is OFF
Room START
Narrow road between lands.
You are stood on a narrow road between The Land and whence you came.
To the north and south are the small foothills of a pair of majestic
mountains, with a large wall running round. To the west the road
continues, where in the distance you can see a thatched cottage opposite
an ancient cemetery. The way out is to the east, where a shroud of
mist covers the secret pass by which you entered The Land.
rain - 
 
----*A playful rabbit snuffles round your feet.
 
----*

```

**Comment by quentinnuk** [comment]
I have also confirmed that the MUD source text files (zip file) are older than the MUD tape and are not compatible. There are less rooms in the MUD source text files than the MUD tape files and DBASE from one source will not compile the other source.

**Comment by larsbrinkhoff** [comment]
Congratulations!  Great job!

**Comment by lts-rad** [comment]
Does this work in an emulator, such as klh10? Is there a tutorial for how to get 7.04 running and try?

**Comment by larsbrinkhoff** [comment]
I'm quite sure Quentin doesn't have his own PDP-10, and is using some emulator.  
Here is the whole adventure so far: https://www.quentin.org.uk/tag/pdp10/

This seems to have a guide for TOPS-10 7.04: http://www.asun.net/pdp10/

**Comment by quentinnuk** [comment]
Yes, running mud on tops 10 on simh using a ks10 cpu. I built it from scratch but there is a tops-10 7.03 disk image that can be downloaded from another site. When I get a moment I’m going to package up a turnkey tops-10 system with mud and adventure installed. My stuff at https://www.quentin.org.uk/category/retro-computing/ may help.

**Comment by lts-rad** [comment]
I was able to follow the instructions. The most confusing part was how to get the files over to richard's PPN, that was slightly frustrating, and I managed to corrupt my disk so that PPN had a UFD file i couldn't update. After starting with a disk backup, and trying again, I managed to get the following

```
.run mud


 
ESSEX UNIVERSITY: Multi-User Dungeon
                                     
This Mud created: 28th February 1984 at 20:50:58
Welcome! By what name shall I call you?
*silence
Creating new persona

What sex do you wish to be?
*male
OK
Hello, Silence!
                
^C trap is OFF
Narrow road between lands.
You are stood on a narrow road between The Land and whence you came.
To the north and south are the small foothills of a pair of majestic
mountains, with a large wall running round. To the west the road
continues, where in the distance you can see a thatched cottage opposite
an ancient cemetery. The way out is to the east, where a shroud of
mist covers the secret pass by which you entered The Land.
 
*A playful rabbit snuffles round your feet.
 
*
```

**Comment by quentinnuk** [comment]
I have been doing some further work on the Stamford source and also the tape source. I can now confirm the the Stamford source appears to be from 1986 and the tape source appears to be from 1984. The stamford source can be made to compile and run, but there are issues that need fixing before it will. Several of the game files, MUD.TXT, TXTCBT.GET, TXTRMS.GET and TXTTXT.GET have (I think) high bit errors in them which cause DBASE to halt. To fix the game files, you just need to open them in SOS and then ECB to save. This makes the files parse through DBASE and allows DBASE to generate a MUD.DMP file. The next step is that DBASE tries to build a new MUD.EXE by (I think) telling Monitor to load MUD.EXE in low-seg and MUD.DMP in high-seg and then doing a SSAVE to generate a new MUD.EXE and also outputting all the MUD.??M game database files. This does not appear to work correctly with the 86 code, I think this might be because DBASE is still trying to use NSSAVE to save MUD but this fails as it is not supported by Monitor 7.04. Immediately after this in RUN MUD but MUD is missing the high-seg so "Something amazingly magical" happens. Im working on the fix, but it is somewhere in the MACRO-10 code in DBASE.BCL or in MBOOTS.MAC, which is where the message comes from. I base my hypothesis for this on the fact that the 84 DBASE does exactly this, but does it in a way that makes it transparent that NSSAVE failed, and therefore still allows you to SSAVE the core as MUD and produce and complete MUD.EXE

**Comment by quentinnuk** [comment]
Emailing richard, he thinks that the high seg linker parameters are wrong for this version and using the 84 MUD.MIC is not helping as they high seg location was individual to each compiled version. I have tried amending the 84 MUD.MIC to use what I believe to be the set:.high. should be for 86 (501501), but that gives a link time PC error (?Illegal memory reference at user PC 602205). More to work out I think.

**Comment by quentinnuk** [comment]
OK, I got it working! Need to compile and run on 2011,2776 but then it all works. You need to amend MUD.MIC to do /set:.high.:502700 and it works. Amazing!

**Comment by quentinnuk** [comment]
I will update the sources on the source tree to reflect working environment and also write up compilation and operating instructions shortly.

**Comment by larsbrinkhoff** [comment]
Good job!

It would be interesting to try running MUD on ITS, but ... lack of time.

**Comment by quentinnuk** [comment]
Im closing this issue now as it is possible to get both tape MUD and the MUD source supplied by Richard Bartle to compile from scratch and execute using the updated files and the guidance I have written in the read.md.
