### ISSUE TITLE
MUD86.tap doesn't appear to be a valid 

### ISSUE THREAD

**Issue by robmayes69** [PDP-10/MUD1#6]
I encounter the following message when attempting to restore via the backup program:

![image](https://user-images.githubusercontent.com/71886692/134389692-5494197e-e1e1-4fa4-ae71-8992b07757f7.png)

**Comment by quentinnuk** [comment]
The first restore worked but didn’t find any files matching the null argument, so when you tried the second restore the tape had advanced beyond the backup file and was empty. You needed to /rewind before the second restore attempt.
