### ISSUE TITLE
Can't build from source

### ISSUE THREAD

**Issue by 13spacemen** [PDP-10/MUD1#7]
I have BCPL in [1,4], I Kermit'd the source files to [2011,2776]
I log in as operator (ppn 1,2) and ```r setsrc``` ```cp [2011,2776]``` to the  directory

I do mud m, do mud dm, and then when I run dbase it errors

```
.dir


1       DBA     4  <057>   15-Sep-23    DSKB:   [2011,2776]
2       DBA     6  <057>   15-Sep-23
5       DBA     2  <057>   15-Sep-23
6       DBA     2  <057>   15-Sep-23
7       DBA     2  <057>   15-Sep-23
ALMANA  DBA     2  <057>   15-Sep-23
BOOK    DBA     1  <057>   15-Sep-23
DBADAT  MAC     7  <057>   15-Sep-23
DBASE   BCL    85  <057>   15-Sep-23
DUNGEN  GET    39  <057>   15-Sep-23
LOGBOO  DBA     2  <057>   15-Sep-23
MBOOTS  MAC    44  <057>   15-Sep-23
MUD     BOX    26  <057>   15-Sep-23
MUD     MIC     4  <057>   15-Sep-23
MUD     SUB     2  <057>   15-Sep-23
MUD     TXT   528  <057>   15-Sep-23
MUD0    BCL     9  <057>   15-Sep-23
MUD1    BCL    22  <057>   15-Sep-23
MUD2    BCL    23  <057>   15-Sep-23
MUD3    BCL    15  <057>   15-Sep-23
MUD4    BCL    13  <057>   15-Sep-23
MUD5    BCL   104  <057>   15-Sep-23
MUD6    BCL    35  <057>   15-Sep-23
MUD7    BCL    21  <057>   15-Sep-23
MUD8    BCL    44  <057>   15-Sep-23
MUDDLM  PDF   378  <057>   15-Sep-23
MUDLIB  BCL    93  <057>   15-Sep-23
MUDLIB  GET    26  <057>   15-Sep-23
MUDTXT  SUB     1  <057>   15-Sep-23
README  MD      1  <057>   15-Sep-23
TXTBTM  GET    21  <057>   15-Sep-23
TXTCBT  GET     5  <057>   15-Sep-23
TXTCSY  GET     1  <057>   15-Sep-23
TXTDAC  GET     4  <057>   15-Sep-23
TXTDMN  GET     2  <057>   15-Sep-23
TXTHRS  GET     1  <057>   15-Sep-23
TXTLEV  GET     1  <057>   15-Sep-23
TXTMAP  GET     1  <057>   15-Sep-23
TXTMTN  GET     2  <057>   15-Sep-23
TXTOBJ  GET     3  <057>   15-Sep-23
TXTOSY  GET     2  <057>   15-Sep-23
TXTRMS  GET     2  <057>   15-Sep-23
TXTTOP  GET     7  <057>   15-Sep-23
TXTTXT  GET    21  <057>   15-Sep-23
TXTVOC  GET     1  <057>   15-Sep-23
VALLEY  TXT    95  <057>   15-Sep-23
DBADAT  REL     9  <057>   15-Sep-23
MBOOTS  REL     4  <057>   15-Sep-23
MUD0    REL     6  <057>   15-Sep-23
MUD1    REL    25  <057>   15-Sep-23
MUD2    REL    27  <057>   15-Sep-23
MUD3    REL    21  <057>   15-Sep-23
MUD4    REL    17  <057>   15-Sep-23
MUD5    REL   124  <057>   15-Sep-23
MUD6    REL    49  <057>   15-Sep-23
MUD7    REL    32  <057>   15-Sep-23
MUD8    REL    58  <057>   15-Sep-23
MUDLIB  REL    95  <057>   15-Sep-23
MUD     EXE   296  <057>   15-Sep-23
DBASE   REL    93  <057>   15-Sep-23
DBASE   EXE   196  <057>   15-Sep-23
  Total of 2762 blocks in 61 files on DSKB: [2011,2776]

.run dbase

initialisation used 1928
persona used 0
combat 
No. of table entries expected
```

I tried the .tap files in the zip branch on github, those don't compile or work either

logging in as a new user richard[2011,2776] and trying to compile, i can do mud m and do mud dm
but it errors with "BCPLJUMPTOZEROJTZ" which I have to exit out of with ^C

**Comment by larsbrinkhoff** [comment]
Did you follow @quentinnuk's instructions as per https://www.quentin.org.uk/tag/pdp10/?

I think these are the blog posts in order:
1. https://www.quentin.org.uk/2018/02/23/essex-bcpl-pre-requisites/
2. https://www.quentin.org.uk/2018/02/25/installing-bcpl/
3. https://www.quentin.org.uk/2018/03/27/fixing-bcpl/
4. https://www.quentin.org.uk/2018/03/27/getting-in-the-mud/
5. https://www.quentin.org.uk/2018/04/09/mud-from-tape/
6. https://www.quentin.org.uk/2018/12/08/a-drier-part-of-the-swamp/
7. https://www.quentin.org.uk/2018/12/08/building-mud-84-from-source/
8. https://www.quentin.org.uk/2018/12/08/building-mud-86-from-source/

**Comment by 13spacemen** [comment]
Yup, even followed the TOPS-10 disk build from scratch instructions too.
I have ENQ/DEQ on my users set to 200 as well
Everything with BCPL is fine, the libs are present in [1,4], and I can build MUD itself which is in BCPL, just not its database (dbase.exe)

I also faced problems with the '84 and '86 tapes. Those compiled MUD and built the database fine, but complained about a missing persona file (mud..pm) ```I don't seem to be able to access :F.MUD[166055000000,0], it's
not your fault, sorry.```, or just doesn't let me in ```isn't available at the moment. Try again tomorrow?```

**Comment by 13spacemen** [comment]
Update: I finally built the dbase. Kermit apparently messed up the .txt and .get files
So you must ```sos mud.txt``` and then ```ecb``` and do this for every .txt and .get file
Then run dbase works fine

I am still having problems with actually loading into the game, both with the operator [1,2] ppn and with richard[2011,2776]

**Comment by 13spacemen** [comment]
Success! I had to restart simh a couple of times but I finally loaded in MUD!
```
.run mud


 
ESSEX UNIVERSITY: Multi-User Dungeon.
                                      
This Mud created: 15th September 2023 at 14:53:16
Origin of version: 15:06:55.
Welcome! By what name shall I call you?
*
```

I built the MUD BCPL source and database as operator[1,2], set all files to <055> protection, I set "ENQ/DEQ" and "IPCF" to 500 in REACT for user "richard[2011,2776]", and after restarting simh and logging as richard and doing run mud it worked

**Comment by quentinnuk** [comment]
Several things here, all of which are covered in the my blog but not necessarily very clearly.

First look at the comments and discussion on this page https://www.quentin.org.uk/2018/12/08/building-mud-86-from-source/#comment-35967

That page covers the TXT file corruption you get using KERMIT on TOPS-10 talking to c-kermit on *nix or windows.

Second, when you are restoring to [2011,2776], rather than using the Op account [1,2], login in as [2011,2776] and restore the files as that ppn. See FAQs below on mounting and restoring as a standard user rather than OPR [1,2].

https://www.quentin.org.uk/tops-10-faq/#qaef-172
https://www.quentin.org.uk/tops-10-faq/#qaef-173

The issue: `I don't seem to be able to access :F.MUD[166055000000,0], it's
not your fault, sorry.` is caused by the wrong protection of the .PM files. This is what happens when MUD can’t read/write/update the persona file (MUD..PM). To correct this, in the executable directory ensure that MUD..PM has a protection of <022>. All other files should probably be <055>. This is covered in the blog post https://www.quentin.org.uk/2018/04/09/mud-from-tape/

**Comment by 13spacemen** [comment]
@quentinnuk The problem with the MUD..PM issue is that, there is no MUD..PM file until I load into MUD. I did .dir many times and there was no MUD..PM file, nor could I transfer one over with Kermit (just became MUD.PM, single dot). 

When I finally loaded into MUD with the richard PPN at the end, only then was a MUD..PM file created

**Comment by quentinnuk** [comment]
For info, my MUD executable directory is [2011,2011] and looks like this:

```
1	DBA     4  <022>   25-Jan-84	DSKB:	[2011,2011]
2	DBA     6  <022>   19-Jan-84
5	DBA     2  <022>   25-Jan-84
6	DBA     2  <022>   14-Feb-84
7	DBA     2  <022>   21-Nov-83
LOGBOO	DBA     1  <022>    9-Aug-22
ALMANA	DBA     2  <022>   25-Feb-19
BOOK	DBA     1  <022>   23-Feb-84
MUD	.RM   144  <055>   14-Jan-19
MUD	.TM   154  <055>   14-Jan-19
MUD	.OM    46  <055>   14-Jan-19
MUD	.MM     4  <055>   14-Jan-19
MUD	.CM     5  <055>   14-Jan-19
MUD	.GM    40  <055>   14-Jan-19
MUD	EXE   492  <055>   16-Feb-19
READ	MUD     2  <057>    1-Mar-84
READ	ME      1  <057>    1-Mar-84
POWER	EXE    72  <057>   12-Jan-19
MUD	WIZ     1  <055>   12-Jan-19
VALLEY	.RM    43  <055>   14-Jan-19
VALLEY	.TM    29  <055>   14-Jan-19
VALLEY	.OM     8  <055>   14-Jan-19
VALLEY	.MM     1  <055>   14-Jan-19
VALLEY	.CM     5  <055>   14-Jan-19
VALLEY	.GM    20  <055>   14-Jan-19
VALLEY	EXE   368  <055>   18-Feb-19
MUD	.PM     4  <422>   12-Sep-23
LETTER	BOX     1  <477>    6-May-20
ACCT	LST     0  <057>   22-Feb-21
  Total of 1460 blocks in 29 files on DSKB: [2011,2011]
```

My MUD build directory is [2011,2776] and looks like this:

```
MUD84	SFD     1  <055>    6-Dec-18	DSKB:	[2011,2776]
MUD86	SFD     1  <055>    7-Dec-18
MUD	MAS   594  <057>   12-Dec-18
SUBFIL	EXE    56  <057>   15-Sep-78	3B(13)
MUD	SUB     2  <057>   21-Feb-18
MUD	MIC     4  <057>    7-Dec-18
MUD	BOX    26  <057>   21-Feb-18
DUNGEN	GET    39  <057>   21-Feb-18
MUDLIB	GET    25  <057>   21-Feb-18
DBASE	BCL    84  <057>   21-Feb-18
MUD0	BCL     9  <057>   21-Feb-18
MUD1	BCL    22  <057>   21-Feb-18
MUD2	BCL    23  <057>   21-Feb-18
MUD3	BCL    15  <057>   21-Feb-18
MUD4	BCL    12  <057>   21-Feb-18
MUD5	BCL   104  <057>   21-Feb-18
MUD6	BCL    34  <057>   21-Feb-18
MUD7	BCL    20  <057>   21-Feb-18
MUD8	BCL    44  <057>   21-Feb-18
MUDLIB	BCL    92  <057>   21-Feb-18
MBOOTS	MAC     6  <057>    7-Dec-18
POWER	BCL    32  <057>    7-Dec-18
DBADAT	MAC     7  <057>   21-Feb-18
  Total of 1252 blocks in 23 files on DSKB: [2011,2776]
```

**Comment by quentinnuk** [comment]
> When I finally loaded into MUD with the richard PPN at the end, only then was a MUD..PM file created

Yes, it gets created on first run if it does not already exist. You need to be crafty with the MUD..PM files as it is a crude form of security by having two stops in the filename as most TOPS-10 utilities dont handle that well. The key to it is to use a wildcard to work around the name.
