### ISSUE TITLE
?MUD.SAV not found

### ISSUE THREAD

**Issue by Alena-03** [PDP-10/MUD1#8]
I try typing run mud into the TOPS 10 prompt, all set up properly, and this is all I get

**Comment by quentinnuk** [comment]
Have you got a MUD.EXE in your directory? Are you using RUN MUD (not R MUD)?

**Comment by Alena-03** [comment]
Ah! well, i found out about the BCPL install stuff, this is as far as i
have gotten

**Comment by quentinnuk** [comment]
The quickest way to get MUD running on TOPS-10 7.04 is to restore from the MUD86.TAP tape file that is in the ZIP branch of this repo. Once you have that, create a PPN of [2011,2776] with ENQ-DEQ and IPF privileges and then restore the tape to that account. Once done you should be able to RUN MUD and use the persona "richard". You do not need BCPL for this to work as it is statically linked. 

Further details at https://www.quentin.org.uk/2018/04/09/mud-from-tape/

**Comment by Alena-03** [comment]
Just quick question, what do i type in to mount?

**Comment by quentinnuk** [comment]
See the FAQ https://www.quentin.org.uk/tops-10-faq/#qaef-172
