### ISSUE TITLE
Any idea where to find the C++ version?

### ISSUE THREAD

**Issue by 0wwafa** [PDP-10/MUD1#9]
I know there is a C++ version (which Stanford 'acquired' 10 years ago).
Any idea where to find it?

Also, at the time there was another M.U.D. called AMP.
I searched everywhere... it would be nice to have that too.

**Comment by quentinnuk** [comment]
It is in C, not C++, and the author of the code is Viktor Toth. It is not publicly available other than to inspect at Stanford. If you want to contact Viktor, your best bet is through the [www.british-legends.com](http://ww.british-legends.com) website.
